
server:
  port: 8080

spring:
  application:
    name: STUDENT-SERVICE


  datasource:
    url: 
    username: admin
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    profile: local


  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enable: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: atreeelections@gmail.com
    password: tvlr aguf pvcx uefr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
